xi.help.register{
    type = "Trait",
    name = "Tenacity",

    description = {
        "Passive trait: Tenacity.",
    },

    jobs = {
        RUN = {
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 5, rank = 1, value = 5 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 20, rank = 2, value = 7 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 35, rank = 3, value = 9 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 55, rank = 4, value = 11 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 60, rank = 5, value = 13 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
            { level = 70, rank = 6, value = 15 },
        },

    },

    notes = {
        "Values shown are total bonuses at each rank.",
        "Tuned for level 75-cap environment.",
    },

    aliases = {
        "tenacity",
    },
}
